{{- if .Values.route.enabled -}}
{{- $fullName := include "openwebui.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.subdomain }}
  subdomain: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    {{- if .Values.oauth.enabled }}
    targetPort: oauth
    {{- else }}
    targetPort: http
    {{- end }}
  {{- if or .Values.route.tls.enabled .Values.oauth.enabled }}
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- if .Values.oauth.enabled }}
    {{- if .Values.route.tls.enabled }}
    termination: reencrypt
    {{- else }}
    termination: passthrough
    {{- end }}
    {{- else }}
    termination: edge
    {{- end }}
  {{- end }}
{{- end }}
