---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwebui.fullname" . }}
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
data:
  WEBUI_SECRET_KEY:  {{ randAlphaNum 12 | b64enc }}
  OPENAI_API_KEYS: {{ tpl (include "openwebui.openai-api-keys" .) . | b64enc | quote }}
{{- if .Values.route.oauth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwebui.fullname" . }}-proxy-session
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
data:
  session_secret: {{ randAlphaNum 32 | b64enc }}
{{- end }}
