apiVersion: v1
kind: Service
metadata:
  name: {{ include "openwebui.fullname" . }}
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
  {{- if .Values.oauth.enabled }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "openwebui.fullname" . }}-proxy-svc-tls
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.oauth.enabled }}
    - port: 8443
      targetPort: oauth
      protocol: TCP
      name: oauth
    {{- end }}
  selector:
    {{- include "openwebui.selectorLabels" . | nindent 4 }}
