{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openwebui.serviceAccountName" . }}
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.oauth.enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "openwebui.fullname" . }}"}}'
    {{- end }}
automountServiceAccountToken: {{ or .Values.serviceAccount.automount .Values.oauth.enabled }}
{{- end }}
