---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "vllm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "vllm.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "vllm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vllm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and (eq .Values.configuration.modelStorage.type "image") (eq .Values.configuration.modelStorage.image.type "modelCar") }}
      shareProcessNamespace: true
      initContainers:
        - name: modelcar-init
          image: {{ .Values.configuration.modelStorage.image.reference }}
          command:
            - /app/entrypoint.sh
          args:
            - check
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: modelcar-mount
              mountPath: /app
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - /bin/sh
          args:
            {{- if .Values.configuration.argsOverride }}
              {{- toYaml .Values.configuration.argsOverride | nindent 12 }}
            {{- else }}
            - -c
            - >-
              vllm serve
              {{- if eq .Values.configuration.modelStorage.type "image" }}
              {{ .Values.configuration.modelStorage.rootDir }}/.modelcar
              --served-model-name={{ .Values.configuration.modelReference }}
              {{- else }}
              {{ .Values.configuration.modelReference }}
              {{- end }}
              --port {{ .Values.service.port }}
              {{- range .Values.configuration.extraArgs }}
              {{ quote . }}
              {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "vllm.fullname" . }}
            {{- if and (ne .Values.configuration.modelStorage.type "image") .Values.configuration.hfModelDownload.enabled }}
            - secretRef:
                name: {{ include "vllm.fullname" . }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
            - name: model-storage
        {{- if and (eq .Values.configuration.modelStorage.type "image") (eq .Values.configuration.modelStorage.image.type "modelCar") }}
              mountPath: {{ .Values.configuration.modelStorage.rootDir }}/.modelcar
            - name: tmp-home
              mountPath: {{ .Values.configuration.modelStorage.rootDir }}
        - name: modelcar
          image: {{ .Values.configuration.modelStorage.image.reference }}
          command:
            - /app/entrypoint.sh
          args:
            - mount
            - {{ .Values.configuration.modelStorage.rootDir }}/.modelcar
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: model-storage
              mountPath: {{ .Values.configuration.modelStorage.rootDir }}/.modelcar
            - name: modelcar-mount
              mountPath: /app
        {{- else }} {{/* this is the model-storage mount for the main container when not using an image */}}
              mountPath: {{ .Values.configuration.modelStorage.rootDir }}
        {{- end }}
        {{- if .Values.oauth.enabled }}
        - name: oauth-proxy
          image: {{ .Values.oauth.image.registry }}/{{ .Values.oauth.image.repo }}:{{ .Values.oauth.image.tag }}
          args:
            - --provider=openshift
            - --pass-basic-auth=false
            - --https-address=:8443
            - --http-address=
            - --email-domain=*
            - --upstream=http://localhost:{{ .Values.service.port }}
            - --openshift-service-account={{ include "vllm.serviceAccountName" . }}
            - --tls-key=/etc/tls/private/tls.key
            - --tls-cert=/etc/tls/private/tls.crt
            - --cookie-secret-file=/etc/proxy/secrets/session_secret
            - --openshift-ca=/etc/pki/tls/cert.pem
            - --openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --openshift-ca=/etc/ocp-injected-certs/ca-bundle.crt
            - >
              --openshift-sar={{ tpl .Values.oauth.sarTemplate . }}
          ports:
            - containerPort: 8443
              name: oauth
          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-svc-tls
            - mountPath: /etc/proxy/secrets
              name: proxy-session
            - mountPath: /etc/ocp-injected-certs
              name: proxy-ca
        {{- end }}
      volumes:
        - name: model-storage
        {{- if eq .Values.configuration.modelStorage.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "vllm.fullname" . }}-storage
            readOnly: {{ not .Values.configuration.hfModelDownload.enabled }}
        {{- else if eq .Values.configuration.modelStorage.type "emptyDir" }}
          emptyDir:
            sizeLimit: {{ .Values.configuration.modelStorage.size }}
            {{- with .Values.configuration.modelStorage.emptyDir }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- else if eq .Values.configuration.modelStorage.type "image" }}
        {{- if eq .Values.configuration.modelStorage.image.type "modelCar" }}
          emptyDir: {}
        - name: modelcar-mount
          configMap:
            name:  {{ include "vllm.fullname" . }}-modelcar-mount
            defaultMode: 493
        - name: tmp-home
          emptyDir: {}
        {{- end }}
        {{- end }}
        {{- if .Values.oauth.enabled }}
        - name: proxy-svc-tls
          secret:
            secretName: {{ include "vllm.fullname" . }}-proxy-svc-tls
        - name: proxy-session
          secret:
            secretName: {{ include "vllm.fullname" . }}-proxy-session
        - name: proxy-ca
          configMap:
            name: {{ include "vllm.fullname" . }}-ocp-injected-certs
        {{- end }}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.configuration.shm.size }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
