{{- if .Values.oauth.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vllm.fullname" . }}-view
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
    apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - {{ include "vllm.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vllm.fullname" . }}-view
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vllm.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vllm.fullname" . }}-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ include "vllm.serviceAccountName" . }}-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "vllm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
