{{- if and (ne .Values.configuration.modelStorage.type "image") .Values.configuration.hfModelDownload.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  HUGGING_FACE_HUB_TOKEN: {{ .Values.configuration.hfModelDownload.huggingfaceToken | b64enc | quote }}
{{- end }}
{{- if .Values.oauth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}-proxy-session
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  session_secret: {{ .Values.oauth.sessionSecret | default (randAlphaNum 32) | b64enc }}
{{- end }}
