{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vllm.serviceAccountName" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.oauth.enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "vllm.fullname" . }}"}}'
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ or .Values.serviceAccount.automount .Values.oauth.enabled }}
{{- end }}
